[versions]
converterGson = "2.9.0"
retrofit = "2.9.0"
koinAndroid = "3.3.0"
fragmentKtx = "1.8.8"

java = "VERSION_1_8"

# Build constants
minSdk = "26"
compileSdk = "36"
targetSdk = "33"

# Detekt
detekt = "1.23.3"
detektTwitterComposeRules ="0.0.26"

[libraries]

# Detekt
staticAnalysis-detektPlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
staticAnalysis-detektCli = { module = "io.gitlab.arturbosch.detekt:detekt-cli", version.ref = "detekt" }
staticAnalysis-detektApi = { module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detekt" }
staticAnalysis-detektTest = { module = "io.gitlab.arturbosch.detekt:detekt-test", version.ref = "detekt" }
staticAnalysis-detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
staticAnalysis-detektLibraries = { module = "io.gitlab.arturbosch.detekt:detekt-rules-libraries", version.ref = "detekt" }
staticAnalysis-detektTwitterComposeRules = { module = "com.twitter.compose.rules:detekt", version.ref = "detektTwitterComposeRules" }

# AndroidX
androidX-core = "androidx.core:core-ktx:1.12.0"
androidX-appCompat = "androidx.appcompat:appcompat:1.6.1"

# UI layer libraries
ui-material = "com.google.android.material:material:1.10.0"
ui-constraintLayout = "androidx.constraintlayout:constraintlayout:2.1.4"

# Unit tests
unitTests-junit = "junit:junit:4.13.2"

# UI tests
uiTests-junitExt = "androidx.test.ext:junit:1.1.5"
uiTests-espressoCore = "androidx.test.espresso:espresso-core:3.5.1"

# Retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }

# Koin
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }

# Fragment
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }

[bundles]
